name: Docker
on: push
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    
 jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v2
      - name: Build the docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
  uses:
  with:
    username: ${{ secrets.DOCKER_USERNAME }}
    password: ${{ secrets.DOCKER_PASSWORD }}
    repository: mpj347/Docker
    tag_wirh_ref: true
    add_git_labels: true
    always_pull: true
    target=mytarget
