name: Docker Image
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
    
 jobs:
   build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v1
        - name: Build and Push Image
          run:
          echo "${{ secrets.DOCKER_PASSWORD }} | docker login -u "mpj347" --password-stdin
          docker image build -t mpj347/Docker:v1
          docker push mpj347/Docker
      
 
